### ISSUE TITLE
Token Error : malformed auth code

### ISSUE THREAD

**Issue by atulchourasiya** [atulchourasiya/QuickNote#1]
hi everyone 
I am trying to solve this malformed auth code error for two days 
but I cant figured it out
this is the error I get
TokenError: Malformed auth code.
    at Strategy.OAuth2Strategy.parseErrorResponse (/var/task/node_modules/passport-oauth2/lib/strategy.js:373:12)
    at Strategy.OAuth2Strategy._createOAuthError (/var/task/node_modules/passport-oauth2/lib/strategy.js:420:16)
    at /var/task/node_modules/passport-oauth2/lib/strategy.js:177:45
    at /var/task/node_modules/oauth/lib/oauth2.js:191:18
    at passBackControl (/var/task/node_modules/oauth/lib/oauth2.js:132:9)
    at IncomingMessage.<anonymous> (/var/task/node_modules/oauth/lib/oauth2.js:157:7)
    at IncomingMessage.emit (node:events:539:35)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

this app is live at https://quicknote.cyclic.app

**Comment by Vinitvh** [comment]
Hi @atulchourasiya. My I know what all solutions you tried?

**Comment by atulchourasiya** [comment]
@Vinitvh  I have try setting accessType :'offline' , decodeUrl on auth code but nothing works 
i think the problem is in the refresh token or something but i cant figure it out

**Comment by Vinitvh** [comment]
@atulchourasiya Okay, let me run this locally and see what's wrong. I have a suggestion, Please update your `README` with instruction to set up your project locally, so that if any wants to help they can do so without referring to docs.

**Comment by atulchourasiya** [comment]
its was a cyclic.sh error i try to deploy it in render and it fixes everything
